### ISSUE TITLE
About the implementations of SAHP and THP

### ISSUE THREAD

**Issue by zhjcp** [yangalan123/anhp-andtt#5]
Why is it said that "Please note that the RMSE and Accuracy stuffs in the training log is not reliable" for SAHP and THP ?

**Comment by yangalan123** [comment]
Hi, thanks for raising this issue! The evaluation (RMSE and Accuracy computation) part for SAHP and THP is "not reliable" as we want to evaluate the model as a generative model rather than a discriminative model (see a more detailed explanation here: https://github.com/yangalan123/anhp-andtt/issues/2#issuecomment-1179113930 ), which necessitates running a thinning algorithm to get an unbiased estimation for future event types and their time given the history (see a more elaborated explanation of thinning algorithm here: https://github.com/yangalan123/anhp-andtt/issues/3#issuecomment-1203451115). However, doing that in training time can be time-consuming as we cannot parallelize the sequential rejection sampling process for Monte-Carlo estimation. We do have a separate testing package implementing the thinning algorithm for both SAHP and THP. I hope that the explanation is clear enough and feel free to follow-up.

**Comment by zhjcp** [comment]
Thank you for your feedback. 

As I understand it, there are two main paradigms for event prediction based on neural point processes: (1) those based on the conditional intensity function, such as NHP and SAHP, which use Monte Carlo sampling to determine the time of the next event and predict the event type as the one with the highest conditional intensity value. (2) those based on an additional Predictor, such as THP, which predict the time and type of the next event based on the hidden vector at the latest event and an additional Predictor. If I understand correctly, the former corresponds to what you refer to as the generative model, and the latter corresponds to the discriminative model.

If the current task is event prediction, can we use either method as long as the prediction performance is good?

**Comment by yangalan123** [comment]
Your understanding is mostly correct except that in the original implementation of SAHP, they used [Trapezoidal rule](https://en.wikipedia.org/wiki/Trapezoidal_rule) to estimate the integral instead of running the thinning algorithm. 

> If the current task is event prediction, can we use either method if the prediction performance is good?

Technically speaking, this is **NOT correct** as different types of modeling should have their corresponding evaluation protocols to make a principled and fair comparison. For example, it is not fair to use a discriminative approach to draw predictions from a generative model, as they are not trained to do so. It is also very challenging to apply a generative approach to draw predictions from a discriminative model unless you want to take an energy-based modeling approach and do MCMC sampling, which can be relatively inefficient. 

I would recommend first thinking about what kind of model you want to build. If you do not want a generative model you can draw samples for future events, the participants, and their timing, imputing the missed observation for events, etc., then you can use a similar way as in THP to build a discriminative model. In NLP (sorry that I am more familiar with NLP myself), it is like the problem of building a BERT or building a GPT. BERT mostly works like a summarizer or a feature extractor, but can hardly work to generate future sequences, while GPT can generate very useful sentences but it can be challenging to use GPT as a feature extractor. There is no absolute concept of "correct modeling" and "wrong modeling" here (though evaluation protocol should follow your modeling), as different modeling approaches are mostly like different formulations of the problem that you want to tackle, and you can make trade-offs based on your application considerations.

**Comment by zhjcp** [comment]
Thanks.

Specifically, the task I am currently focusing on is Next Event Prediction, which involves predicting the time and type of the next event given a sequence of historical events. For this task, methods based on conditional intensity functions (such as NHP) and methods based on predictors (such as THP) are both competent. In this context, is it unnecessary to distinguish between generative models and discriminative models, since they are merely techniques using neural point process models to predict the next event?

Besides, my understanding of THP might differ slightly from yours. I believe that THP is more akin to GPT rather than BERT, as both THP and GPT can be categorized under Next Token/Event Prediction Models, which only use the left context (or historical context). In contrast, BERT predicts the masked token based on both the left and right context.

**Comment by zhjcp** [comment]
Additionally, have you read the point process benchmark paper - EasyTPP, published at ICLR24? In this paper, the authors uniformly evaluated all point process models using the Thinning algorithm. However, looking at the experimental results, the RMSE and Type Error Rate for all methods are roughly the same, which seems somewhat problematic.

**Comment by yangalan123** [comment]
Thanks for the follow-ups. Before I answer your questions, I want to first clarify that all of my responses are not pushing or forcing any beliefs -- I do not think I have that authority, and apologize if my tone sounds like so. In the field of TPP, people already take different approaches to evaluation and I as a student have no power or resources to unify it. Instead, I just try to convey what I believe and do an open-minded, gentle discussion with you. 

There are a lot of comments to deal with, so let me explain step-by-step:


> Specifically, the task I am currently focusing on is Next Event Prediction, which involves predicting the time and type of the next event given a sequence of historical events.

Thanks for providing the context. This is the task for almost all the Neural Point Process models. People take different modeling approaches to achieve this goal and each of them has its own merits and limitations. 

> In this context, is it unnecessary to distinguish between generative models and discriminative models, since they are merely techniques using neural point process models to predict the next event?

Sorry, it is hard for me to follow this reasoning. I do not understand why belonging to the same larger family of models establishes the equivalence of these two different modeling approaches. Following this reasoning, we can also say that bidirectional-attentive models (like BERT) and unidirectional-attentive models (like GPT) can use the same method to make a prediction (the former usually necessitates an additional "head" and some fine-tuning, while the latter we currently use prompting + output normalization) as they are both sequential neural models dealing with discrete tokens. But we all know it is not true -- at least we cannot decode from the bi-directional model token-by-token as it already sees the future. I understand there still exist various methods to work around and get "good performance" -- In that case, I think it can be tricky to say the success is from the modeling, but for some other elements accompanying it (like the building success of predictor, greater simplification of problems or better data processing).  

I personally think the concept of the "Neural Point Process" is too broad, as it mostly only defines the modality (continuous-time event streams) and only necessitates a neural model to implement the probabilistic model. It does not enforce any requirements for evaluation. 

> Besides, my understanding of THP might differ slightly from yours. I believe that THP is more akin to GPT rather than BERT, as both THP and GPT can be categorized under Next Token/Event Prediction Models, which only use the left context (or historical context). In contrast, BERT predicts the masked token based on both the left and right context.

I apologize for my bad explanations. Long time not working on TPP fields makes my explanation not appropriate. First, I want to explain that, unidirectional or bi-directional itself is not sufficient for establishing the difference between a generative model and a discriminative model -- Let's start with the definition. I quoted the definition for these two model families below (from [wiki](https://en.wikipedia.org/wiki/Generative_model) ):

> 1. A generative model is a statistical model of the joint probability distribution P(X, Y) on a given observable variable X and target variable Y;[1] A generative model can be used to "generate" random instances (outcomes) of an observation x.
> 2. A discriminative model is a model of the conditional probability P(Y | X=x) of the target Y, given an observation x. It can be used to "discriminate" the value of the target variable Y, given an observation x.
> 3. Classifiers computed without using a probability model are also referred to loosely as "discriminative".

Intuitively, the key difference is what probabilistic model we are working with in prediction in the first place -- do we start with a conditional model P(Y | X=x), or a generative model P(X, Y)? Note, that P(X, Y) can always marginalize to get P(Y | X=x), but we cannot convert P(Y | X=x) to P(X, Y) as we are missing P(X=x). In this sense, a generative model is always more expressive than its discriminative counterpart. 

In THP, the prediction is made following first building an exponential-decay model for P(next_step_time | H=history) and then a multinomial distribution P(next_event_type | H=history, time=next_step_time), so it is a discriminative model rather than a generative model, as every model involved needs some conditioning. 

However, in our model ANHP, we build the joint model $P( (t_0, k_0), (t_1, k_1), ....)$, and in prediction, we marginalize our probabilistic model to get conditional distribution: $P((t, k) | H) = \frac{P((t_0, k_0), (t_1, k_1),..., (t_L, k_L), (t, k))}{\sum_{(t, k)}P((t_0, k_0), (t_1, k_1),..., (t_L,k_L), (t, k))}$. The denominator is intractable to compute, so we seek to MC estimation and run the thinning algorithm to get the prediction practically.   

Why did I previously regard THP more like BERT? You can see that BERT always makes a prediction from a conditional perspective, hardly capable of modeling the joint distribution, and the same as THP. **Through this a bit more rigorous analysis, I should correct myself to say SAHP is also closer to BERT.**  However, our model starts from the joint distribution $P( (t_0, k_0), (t_1, k_1), ....)$ so it is more of a generative model like GPT.  In the text, as the timing is just discrete integers $0,1,2,...T$ this problem is not that obvious. We always know the next time in pure-text modeling, so we do not even bother to model what it would be. (Well, perhaps some recent works on ROPE try to solve long-context problems by modifying positional embeddings, but that goes beyond our discussion scope.)  

I already explained how we can turn a generative model to be a discriminative counterpart above, but I can give more application scenarios -- what if we want to draw multiple future events? what if our observation data is broken, which is almost always the case in real-world data? Multiple proposals of future event pairs (t,k) are racing to become the next one and next-K, or the missing history. 

We believe, in our work, that a generative model combined with the thinning algorithm yields an unbiased and principled way to tackle all these problems (See more analysis in [Mei and Eisner NHP paper Appendix B.3](https://arxiv.org/pdf/1612.09328)).  

> Additionally, have you read the point process benchmark paper - EasyTPP, published at ICLR24? In this paper, the authors uniformly evaluated all point process models using the Thinning algorithm. However, looking at the experimental results, the RMSE and Type Error Rate for all methods are roughly the same, which seems somewhat problematic.

I did not read that paper as I have moved away from the TPP field, though I still spend minimal efforts to maintain a must-read [paper list](https://github.com/yangalan123/TemporalPointProcessPapers) only out of personal interest. I feel I am not in a good position to comment on any experiment results in that paper. But just as a side note -- in my mind, we cannot use the experiment results to make the decision on which evaluation protocol we should use. This is the reversing of cause and effect. 

Thanks for reading so far -- I deeply apologize for my bad explanation. There are so many important technical details and I have moved away for a quite long time. So it is really hard for me to gradually recall some theories and perspectives. For the EasyTPP paper, my best advice would be you contact the authors of that paper if you have questions on their experiment results. Hope that answers your questions.

**Comment by zhjcp** [comment]
Thank you for your patient reply; it has enhanced my understanding of the neural point process. I think I should learn more about the Thinning algorithm and discuss it with you subsequently.

**Comment by yangalan123** [comment]
Close this issue as there has been no response for more than three months. Feel free to reopen it.
